version: '{branch}.{build}'
branches:
  only:
  - master
skip_non_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
build:
  project: NetFrameworkChecker.sln
  verbosity: minimal
artifacts:
- path: NetFrameworkChecker\bin\Release\NetFrameworkChecker.exe
  name: NetFrameworkChecker.exe
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: $(APPVEYOR_REPO_TAG_NAME)
  auth_token:
    secure: 8rFG2X11nZArE5N8zrYpGcSfP9XTvaMwZ9DIho9DjaR2GPFv0J+BU7qdvA2UCzUi
  artifact: NetFrameworkChecker.exe
  draft: false
  on:
    APPVEYOR_REPO_TAG: true
notifications:
- provider: Email
  to:
  - greenzest@gmail.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true